[package]
name = "c3p0_tests_migrate"
license = "MIT"
version = "0.50.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "sqlite", "json"]

[dependencies]
c3p0 = { path = "../c3p0", version = "0.50.1" }

[dev-dependencies]
rand = "0.7"
testcontainers = "0.9"
tokio = { version = "0.2", features = ["full"] }

[features]
default = []

mysql_blocking = ["c3p0/mysql_blocking_migrate"]
pg = ["c3p0/pg_migrate"]
pg_blocking = ["c3p0/pg_blocking_migrate"]
sqlite_blocking = ["c3p0/sqlite_blocking_migrate"]
