[package]
name = "c3p0_tests_migrate"
license = "MIT"
version = "0.21.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "sqlite", "json"]

[dependencies]
# mysql feature
c3p0_mysql = { path = "../c3p0_mysql", version = "0.21.0", optional = true, features = ['migrate']}

# pg feature
c3p0_pg = { path = "../c3p0_pg", version = "0.21.0", optional = true, features = ['migrate'] }

# sqlite feature
c3p0_sqlite = { path = "../c3p0_sqlite", version = "0.21.0", optional = true, features = ['migrate'] }

[dev-dependencies]
lazy_static = "1.3"
maybe-single = "0.4"
rand = "0.7"
testcontainers = "0.8"

[features]
default = []

mysql = ["c3p0_mysql"]
pg = ["c3p0_pg"]
sqlite = ["c3p0_sqlite"]
