[package]
name = "c3p0_tests_migrate"
license = "MIT"
version = "0.60.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "sqlite", "json"]

[dependencies]
c3p0 = { path = "../c3p0", version = "0.60.0" }

[dev-dependencies]
rand = "0.7"
testcontainers = "0.9"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }

[features]
default = []

#mysql = ["c3p0/mysql_migrate"]
postgres = ["c3p0/postgres_migrate"]
#tidb = ["c3p0/tidb_migrate"]