[package]
name = "c3p0_common"
license = "MIT"
version = "0.50.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2"
edition = "2018"
readme = "../README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["c3p0"]

[dependencies]
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"

# feature 'async'
async-trait = {version = "0.1", optional = true }

# feature 'migrate'
include_dir = { version = "0.5", optional = true }
md-5 = { version = "0.8", optional = true }
same-file = { version = "1", optional = true }
walkdir = { version = "2.3", optional = true }

[dev-dependencies]
static_assertions = "1"

[features]
default = []

async = ["async-trait"]
blocking = []
migrate = ["include_dir", "md-5", "same-file", "walkdir"]
