[package]
name = "c3p0_common"
license = "MIT"
version = "0.20.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2"
edition = "2018"
readme = "../README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["c3p0"]

[dependencies]
err-derive = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# for migrate
include_dir = { version = "0.2", optional = true }
md-5 = { version = "0.8", optional = true }
same-file = { version = "1", optional = true }
walkdir = { version = "2.2", optional = true }

[features]
default = []

migrate = ["include_dir", "md-5", "same-file", "walkdir"]