language: rust

sudo: true

group: edge

rust:
  - stable
  
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV="true"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install libpq-dev libmysqlclient-dev
  
script:
  - cargo install --debug cargo-make
  - cargo make --no-workspace workspace-ci-flow --features pg
