[tasks.build]
args = ["build", "--features", "pg"]

# > cargo make --no-workspace build_all
[tasks.build_all]
script = [
  "cd ./c3p0_common        && cargo build",
  "cd ..",
  "cd ./c3p0_in_memory     && cargo build",
  "cd ..",
  "cd ./c3p0_mysql         && cargo build",
  "cd ..",
  "cd ./c3p0_pg            && cargo build",
  "cd ..",
  "cd ./c3p0_pg_015        && cargo build",
  "cd ..",
  "cd ./c3p0_pg_async      && cargo build",
  "cd ..",
  "cd ./c3p0_sqlite        && cargo build",
  "cd ..",
  "cd ./c3p0               && ./cargo.sh build",
  "cd ..",
  "cd ./c3p0_tests_migrate && ./cargo.sh build",
  "cd ..",
]

# > cargo make --no-workspace test_all
[tasks.test_all]
script = [
  "cd ./c3p0_common        && cargo test",
  "cd ..",
  "cd ./c3p0_in_memory     && cargo test",
  "cd ..",
  "cd ./c3p0_mysql         && cargo test",
  "cd ..",
  "cd ./c3p0_pg            && cargo test",
  "cd ..",
  "cd ./c3p0_pg_015        && cargo test",
  "cd ..",
  "cd ./c3p0_pg_async      && cargo test",
  "cd ..",
  "cd ./c3p0_sqlite        && cargo test",
  "cd ..",
  "cd ./c3p0               && ./cargo.sh test",
  "cd ..",
  "cd ./c3p0_tests_migrate && ./cargo.sh test",
  "cd ..",
]

# > cargo make --no-workspace publish_all
[tasks.publish_all]
script = [
  "cd ./c3p0_common        && cargo publish && sleep 20",
  "cd ..",
  "cd ./c3p0_in_memory     && cargo publish && sleep 20",
  "cd ..",
  "cd ./c3p0_mysql         && cargo publish && sleep 20",
  "cd ..",
  "cd ./c3p0_pg            && cargo publish && sleep 20",
  "cd ..",
  "cd ./c3p0_pg_015        && cargo publish && sleep 20",
  "cd ..",
  "cd ./c3p0_pg_async      && cargo publish && sleep 20",
  "cd ..",
  "cd ./c3p0_sqlite        && cargo publish && sleep 20",
  "cd ..",
  "cd ./c3p0               && cargo publish --features pg",
  "cd ..",
]

