[tasks.build]
args = ["build", "--features", "pg"]

# > cargo make --no-workspace build_all
[tasks.build_all]
script = [
  "cd ./c3p0               && ./cargo.sh build",
  "cd ..",
  "cd ./c3p0_diesel_macro  && cargo build",
  "cd ..",
  "cd ./c3p0_diesel        && cargo build",
  "cd ..",
  "cd ./c3p0_migrate       && ./cargo.sh build",
  "cd ..",
]

# > cargo make --no-workspace test_all
[tasks.test_all]
script = [
  "cd ./c3p0               && ./cargo.sh test",
  "cd ..",
  "cd ./c3p0_diesel_macro  && cargo test",
  "cd ..",
  "cd ./c3p0_diesel        && cargo test",
  "cd ..",
  "cd ./c3p0_migrate       && ./cargo.sh test",
  "cd ..",
]

# > cargo make --no-workspace publish_all
[tasks.publish_all]
script = [
  "cd ./c3p0               && cargo publish --features pg",
  "cd .. && sleep 4",
  "cd ./c3p0_diesel_macro  && cargo publish",
  "cd .. && sleep 4",
  "cd ./c3p0_diesel        && cargo publish",
  "cd .. && sleep 4",
  "cd ./c3p0_migrate       && cargo publish --features pg",
  "cd ..",
]

