# To execute with:
# > cargo make --no-workspace publish_all
[tasks.publish_all]
script = [
  "cargo clean",
  "cargo test",
  "cargo build",
  "cd ./c3p0               && cargo publish",
  "cd .. && sleep 4",
  "cd ./c3p0_diesel_macro  && cargo publish",
  "cd .. && sleep 4",
  "cd ./c3p0_diesel        && cargo publish",
  "cd .. && sleep 4",
  "cd ./c3p0_pg_migrate    && cargo publish",
  "cd ..",
]

