[tasks.build]
args = ["build", "--features", "pg"]

# > cargo make --no-workspace build_all
[tasks.build_all]
script = [
  "cd ./c3p0_common        && cargo build",
  "cd ..",
  "cd ./c3p0_pool_mysql    && cargo build",
  "cd ..",
  "cd ./c3p0_pool_pg       && cargo build",
  "cd ..",
  "cd ./c3p0_pool_sqlite   && cargo build",
  "cd ..",
  "cd ./c3p0_json          && ./cargo.sh build",
  "cd ..",
  "cd ./c3p0_migrate       && ./cargo.sh build",
  "cd ..",
  "cd ./c3p0               && ./cargo.sh build",
  "cd ..",
]

# > cargo make --no-workspace test_all
[tasks.test_all]
script = [
  "cd ./c3p0_common        && cargo test",
  "cd ..",
  "cd ./c3p0_pool_mysql    && cargo test",
  "cd ..",
  "cd ./c3p0_pool_pg       && cargo test",
  "cd ..",
  "cd ./c3p0_pool_sqlite   && cargo test",
  "cd ..",
  "cd ./c3p0_json          && ./cargo.sh test",
  "cd ..",
  "cd ./c3p0_migrate       && ./cargo.sh test",
  "cd ..",
  "cd ./c3p0               && ./cargo.sh test",
  "cd ..",
]

# > cargo make --no-workspace publish_all
[tasks.publish_all]
script = [
  "cd ./c3p0_common        && cargo publish && sleep 4",
  "cd ..",
  "cd ./c3p0_pool_mysql    && cargo publish && sleep 4",
  "cd ..",
  "cd ./c3p0_pool_pg       && cargo publish && sleep 4",
  "cd ..",
  "cd ./c3p0_pool_sqlite   && cargo publish && sleep 4",
  "cd ..",
  "cd ./c3p0_json          && cargo publish --features pg && sleep 4",
  "cd ..",
  "cd ./c3p0_migrate       && cargo publish --features pg && sleep 4",
  "cd ..",
  "cd ./c3p0               && cargo publish --features pg",
  "cd ..",
]

