[package]
name = "c3p0"
license = "MIT"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2"
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
