[package]
name = "c3p0"
license = "MIT"
version = "0.4.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2"
edition = "2018"
readme = "../README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "json", "diesel"]

[dependencies]
err-derive = "0.1"
log = "0.4"
r2d2 = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# mysql feature
mysql_client = { package = "mysql",  version = "16", optional = true }
r2d2_mysql = { version = "16.0", optional = true }

# pg feature
postgres = { version = "0.15", features = ["with-serde_json"], optional = true  }
r2d2_postgres = { version = "0.14", optional = true }

[dev-dependencies]
lazy_static = "1.3"
maybe-single = "0.1"
testcontainers = "0.6"

[features]
default = []

mysql = ["mysql_client", "r2d2_mysql"]
pg = ["postgres", "r2d2_postgres"]
