[package]
name = "c3p0"
license = "MIT"
version = "0.21.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "sqlite", "json"]

[dependencies]
# mysql feature
c3p0_in_memory = { path = "../c3p0_in_memory", version = "0.21.0", optional = true }

# mysql feature
c3p0_mysql = { path = "../c3p0_mysql", version = "0.21.0", optional = true }

# pg feature
c3p0_pg = { path = "../c3p0_pg", version = "0.21.0", optional = true }

# sqlite feature
c3p0_sqlite = { path = "../c3p0_sqlite", version = "0.21.0", optional = true }

[dev-dependencies]
err-derive = "0.1"
lazy_static = "1.3"
maybe-single = "0.4"
rand = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
testcontainers = "0.8"

[features]
default = []

in_memory = ["c3p0_in_memory"]

mysql = ["c3p0_mysql"]
mysql_migrate = ["mysql", "c3p0_mysql/migrate"]

pg = ["c3p0_pg"]
pg_migrate = ["pg", "c3p0_pg/migrate"]

sqlite = ["c3p0_sqlite"]
sqlite_migrate = ["sqlite", "c3p0_sqlite/migrate"]

#tidb = ["mysql"]
#tidb_migrate = ["mysql_migrate"]

#migrate = ["c3p0_migrate"]
