[package]
name = "c3p0"
license = "MIT"
version = "0.8.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "sqlite", "json"]

[dependencies]
serde = "1.0"

# mysql feature
c3p0_pool_mysql = { path = "../c3p0_pool_mysql", version = "0.8.1", optional = true }

# pg feature
c3p0_pool_pg = { path = "../c3p0_pool_pg", version = "0.8.1", optional = true }

# sqlite feature
c3p0_pool_sqlite = { path = "../c3p0_pool_sqlite", version = "0.8.1", optional = true }

# json feature
c3p0_json = { path = "../c3p0_json", version = "0.8.1", optional = true }

# migrate feature
c3p0_migrate = { path = "../c3p0_migrate", version = "0.8.1", optional = true }

[features]
default = []

mysql = ["c3p0_pool_mysql", "c3p0_json/mysql", "c3p0_migrate/mysql"]
pg = ["c3p0_pool_pg", "c3p0_json/pg", "c3p0_migrate/pg"]
sqlite = ["c3p0_pool_sqlite", "c3p0_json/sqlite", "c3p0_migrate/sqlite"]

#json = ["c3p0_json"]

#migrate = ["c3p0_migrate"]
