[package]
name = "c3p0"
license = "MIT"
version = "0.20.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "sqlite", "json"]

[dependencies]
# mysql feature
c3p0_pool_mysql = { path = "../c3p0_pool_mysql", version = "0.20.0", optional = true }

# pg feature
c3p0_pool_pg = { path = "../c3p0_pool_pg", version = "0.20.0", optional = true }

# sqlite feature
c3p0_pool_sqlite = { path = "../c3p0_pool_sqlite", version = "0.20.0", optional = true }

[dev-dependencies]
err-derive = "0.1"
lazy_static = "1.3"
maybe-single = "0.4"
rand = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
testcontainers = "0.6"

[features]
default = []

mysql = ["c3p0_pool_mysql"]
mysql_migrate = ["mysql", "c3p0_pool_mysql/migrate"]

pg = ["c3p0_pool_pg"]
pg_migrate = ["pg", "c3p0_pool_pg/migrate"]

sqlite = ["c3p0_pool_sqlite"]
sqlite_migrate = ["sqlite", "c3p0_pool_sqlite/migrate"]

#migrate = ["c3p0_migrate"]
