[package]
name = "c3p0"
license = "MIT"
version = "0.52.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "sqlite", "json"]

[dependencies]
c3p0_common = { path = "../c3p0_common", version = "0.52.0" }

# mysql feature
c3p0_in_memory = { path = "../c3p0_in_memory", version = "0.52.0", optional = true }

# mysql feature
c3p0_mysql = { path = "../c3p0_mysql", version = "0.52.0", optional = true }

# pg feature
c3p0_pg = { path = "../c3p0_pg", version = "0.52.0", optional = true }

# sqlite feature
c3p0_sqlite = { path = "../c3p0_sqlite", version = "0.52.0", optional = true }

[dev-dependencies]
futures = "0.3"
maybe-single = "0.11"
once_cell = "1.3"
rand = "0.7"
serde = { version = "1.0" , features = ["derive"] }
serde_json = "1.0"
testcontainers = "0.9"
thiserror = "1.0"
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }

[features]
default = []

in_memory_blocking = ["c3p0_in_memory/blocking"]

mysql_blocking = ["c3p0_mysql/blocking"]
mysql_blocking_migrate = ["mysql_blocking", "c3p0_mysql/migrate"]

pg = ["c3p0_pg/async"]
pg_migrate = ["pg", "c3p0_pg/migrate"]
pg_blocking = ["c3p0_pg/blocking"]
pg_blocking_migrate = ["pg_blocking", "c3p0_pg/migrate"]

sqlite_blocking = ["c3p0_sqlite/blocking"]
sqlite_blocking_migrate = ["sqlite_blocking", "c3p0_sqlite/migrate"]
