[package]
name = "c3p0_migrate"
license = "MIT"
version = "0.4.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-postgres."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "postgres", "pg", "json", "diesel"]

[dependencies]
c3p0 = { path = "../c3p0", version = "0.4.0" }
err-derive = "0.1"
include_dir="0.2"
log = "0.4"
md-5 = "0.8"
same-file = "1"
serde = "1.0"
serde_derive = "1.0"
walkdir = "2.2"

[dev-dependencies]
lazy_static = "1.3"
maybe-single = "0.1"
r2d2 = "0.8"
testcontainers = "0.6"

# mysql feature
mysql_client = { package = "mysql", version = "15" }
r2d2_mysql = { version = "15.0" }

# pg feature
postgres = { version = "0.15" }
r2d2_postgres = { version = "0.14" }


[features]
default = []

mysql = ["c3p0/mysql"]
pg = ["c3p0/pg"]