[package]
name = "c3p0_mysql"
license = "MIT"
version = "0.50.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2"
edition = "2018"
readme = "../README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql"]

[dependencies]
c3p0_common = { path = "../c3p0_common", version = "0.50.1" }
log = "0.4"
serde = "1.0"

# feature 'blocking'
mysql_driver_blocking = { package = "mysql", version = "18", optional = true}
r2d2 = { version = "0.8.8", optional = true}

[features]
default = []

blocking = ["c3p0_common/blocking", "mysql_driver_blocking", "r2d2"]
migrate = ["c3p0_common/migrate"]