[package]
name = "c3p0_mysql"
license = "MIT"
version = "0.2.3"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "A good friend for r2d2. Based on rust-mysql-simple."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/ufoscout/c3p0"
repository = "https://github.com/ufoscout/c3p0"
keywords = ["mysql", "json"]

[dependencies]
err-derive = "0.1"
log = "0.4"
mysql = "15.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
lazy_static = "1.3"
maybe-single = "0.1"
r2d2 = "0.8"
r2d2_mysql = "15.0"
testcontainers = "0.6"
